### ISSUE TITLE
TOML configuration file

### ISSUE THREAD

**Issue by TurpinA** [GuillaumeBchd/Styx#2]
We want to create configuration files for our RVP. We choosed the TOML format to do this. For more informations on TOML, you can visit [TOML website](https://toml.io/en/).

Here is an exemple of a TOML file : 

```TOML
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8001, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```

We would like to make it look a lot like the basic configuration file of nginx : 

```NGINX
upstream container {
  server        container:80;
}

server {
  listen        80;
  server_name   my_url.com;

  location / {
    proxy_pass  http://container ;
    auth_basic           "Container's maintainer Area";
    auth_basic_user_file /path/to/user_password_file;
  }
}
```

**Comment by TurpinA** [comment]
First comment

**Comment by AdrienVerdier** [comment]
I started working on the configuration file.

We have now a first version of the TOML file. It will probably need to be changed over time when we will improve our RVP.

You can find it in the configuration_file github branche. 

Here is the content of the TOML file : 

```TOML
title = "Styx Configuration File"

[server]
port = 80
server_name = "my_url"

[Default]
default_route = "route par defaut"

[[hosts]]
name = "google"
entrypoint = "url"
ip = "8.8.8.8"
port = 8080

[[hosts]]
name = "localhost"
entrypoint = "url"
ip = "127.0.0.0"
port = 3606

[[hosts]]
name = "localhost2"
entrypoint = "url"
ip = "127.0.0.0"
port = 8080

[DDOS_Parameters]
max_request = 10000
max_request_per_user = 100
verification_timer = 180 #in seconds
```

**Comment by AdrienVerdier** [comment]
I have written different method to get the current information that are storred inside the configuration file.

This methods will probably need to be change when we will modify the configuration file.

**Comment by AdrienVerdier** [comment]
Modification of the configuration file - waiting for validation. The method to access the configuration file need to be changed

```TOML
title = "Styx Configuration File"

[server]
port = 80
server_name = "my_url"

[Default]
default_route = "route par defaut"

[[sites]]
name = "google"
entrypoint = "url"
addresses = [ "127.0.0.1:8080", "127.0.0.1:8081"]

[[sites]]
name = "localhost"
entrypoint = "url"
addresses = [ "127.0.0.1:8080", "127.0.0.1:8081"]

[[sites]]
name = "localhost2"
entrypoint = "url"
addresses = [ "127.0.0.1:8080", "127.0.0.1:8081"]

[DDOS_Parameters]
max_request = 10000
max_request_per_user = 100
verification_timer = 180 #in seconds
```
